import {
  GraduationCap,
  Award,
  Briefcase,
  Languages,
  Brain,
  Dumbbell,
  Swords,
  Mountain,
  Timer,
  Gamepad2,
  Heart,
  Car,
  Music,
  Crosshair,
  Palette,
  Code,
  BookOpen,
  Target,
  Flag,
  Flame,
  Fish,
  Compass,
  Church,
  Wheat,
  MapPin,
  Anchor,
  Dog,
  Home,
  Wine,
  Flower2,
  Beef,
  CookingPot,
  TreePine,
  Bike,
  Camera,
  Video,
  Hammer,
  Wrench,
  Skull,
  Youtube,
  Cross,
  Scroll,
  Snowflake,
  Castle,
  Building2,
  Plane,
  type LucideIcon,
} from "lucide-react"

export type AchievementRarity = "legendary" | "epic" | "rare" | "common"

export interface Achievement {
  id: string
  title: string
  description: string
  flavor: string
  date: string
  points: number
  rarity: AchievementRarity
  category: string
  icon: LucideIcon
  unlocked: boolean
  inProgress?: boolean
}

export interface AchievementCategory {
  id: string
  label: string
  icon: LucideIcon
  description: string
}

export const categories: AchievementCategory[] = [
  {
    id: "all",
    label: "All Achievements",
    icon: Award,
    description: "View all achievements",
  },
  {
    id: "education",
    label: "Scholar's Path",
    icon: GraduationCap,
    description: "Academic milestones and degrees",
  },
  {
    id: "certifications",
    label: "Marks of Mastery",
    icon: Award,
    description: "Professional certifications earned",
  },
  {
    id: "languages",
    label: "Polyglot",
    icon: Languages,
    description: "Language proficiency achievements",
  },
  {
    id: "experience",
    label: "Veteran's Record",
    icon: Briefcase,
    description: "Professional experience and roles",
  },
  {
    id: "knowledge",
    label: "Loremaster",
    icon: Brain,
    description: "Specialized knowledge and training",
  },
  {
    id: "sanctuaries",
    label: "Sacred Stones",
    icon: Church,
    description: "Cathedrals, churches, and holy sites visited",
  },
  {
    id: "gamedev",
    label: "World Forger",
    icon: Gamepad2,
    description: "Game development and creative projects",
  },
  {
    id: "sports",
    label: "Arena Champion",
    icon: Swords,
    description: "Martial arts and team sports",
  },
  {
    id: "strength",
    label: "Iron Colossus",
    icon: Dumbbell,
    description: "Calisthenics, gym, and feats of strength",
  },
  {
    id: "endurance",
    label: "Endurance Runner",
    icon: Timer,
    description: "Running records and endurance feats",
  },
  {
    id: "mountaineering",
    label: "Peak Seeker",
    icon: Mountain,
    description: "Summits, trails, and alpine adventures",
  },
  {
    id: "charity",
    label: "Heart of Gold",
    icon: Heart,
    description: "Charity work and community service",
  },
  {
    id: "skills",
    label: "Jack of Trades",
    icon: Palette,
    description: "Diverse hobbies, crafts, and life skills",
  },
  {
    id: "licenses",
    label: "Motor & Machine",
    icon: Car,
    description: "Vehicles, licenses, and mechanical mastery",
  },
  {
    id: "fishing",
    label: "Angler's Log",
    icon: Fish,
    description: "Fishing milestones and trophy catches",
  },
  {
    id: "hunting",
    label: "Hunter's Path",
    icon: Crosshair,
    description: "Hunting, butchering, and wilderness skills",
  },
  {
    id: "blacksmith",
    label: "Forge & Anvil",
    icon: Hammer,
    description: "Blacksmithing and metalworking achievements",
  },
  {
    id: "exploration",
    label: "Wayfarer's Atlas",
    icon: Compass,
    description: "Cities, countries, and lands explored",
  },
  {
    id: "homestead",
    label: "Hearthbound",
    icon: Wheat,
    description: "Village life, homecraft, cooking, and stewardship",
  },
  {
    id: "tales",
    label: "Tales & Trials",
    icon: Scroll,
    description: "Random adventures, wild stories, and feats of endurance",
  },
]

export const achievements: Achievement[] = [
  // ===== EDUCATION =====
  {
    id: "bachelors",
    title: "Scholar Initiate",
    description: "Earned a Bachelor's Degree",
    flavor: "\"The first step on the path to knowledge is the hardest \u2014 and the most rewarding.\"",
    date: "Completed",
    points: 50,
    rarity: "epic",
    category: "education",
    icon: GraduationCap,
    unlocked: true,
  },
  {
    id: "masters",
    title: "Arcane Scholar",
    description: "Master's Degree \u2014 In Progress",
    flavor: "\"The final trials of higher learning draw near. Only a few months remain before the title is yours.\"",
    date: "In Progress",
    points: 100,
    rarity: "legendary",
    category: "education",
    icon: GraduationCap,
    unlocked: true,
    inProgress: true,
  },
  {
    id: "published-researcher",
    title: "Chronicler of the Deep",
    description: "Published Researcher \u2014 2nd Author: \"Marine Spatial Planning meets Mixed Reality\"",
    flavor: "\"Your name is etched into the scrolls of academia. Knowledge of the deep seas, bound to the arcane arts of Mixed Reality.\"",
    date: "Published",
    points: 75,
    rarity: "legendary",
    category: "education",
    icon: BookOpen,
    unlocked: true,
  },

  // ===== CERTIFICATIONS (Marks of Mastery) =====
  {
    id: "project-management",
    title: "Warlord Strategist",
    description: "Project Management Professional Certification",
    flavor: "\"Armies are not led by swords alone \u2014 strategy and planning win wars.\"",
    date: "Certified",
    points: 50,
    rarity: "epic",
    category: "certifications",
    icon: Award,
    unlocked: true,
  },
  {
    id: "stanford-game-theory",
    title: "Grandmaster Tactician",
    description: "Stanford Game Theory Certification",
    flavor: "\"You see the game within the game. Every move, a calculated decision.\"",
    date: "Certified",
    points: 60,
    rarity: "legendary",
    category: "certifications",
    icon: Brain,
    unlocked: true,
  },
  {
    id: "fmicodes-win",
    title: "Champion of FMICodes",
    description: "Won Hackathon across all Sofia Universities \u2014 FMICodes: For Art",
    flavor: "\"Against all the guilds of Sofia, your party stood victorious. The Art category bowed to your creation.\"",
    date: "1st Place",
    points: 70,
    rarity: "legendary",
    category: "certifications",
    icon: Award,
    unlocked: true,
  },
  {
    id: "colorado-exercise",
    title: "Scholar of the Body",
    description: "University of Colorado Boulder: Science of Exercise Certification",
    flavor: "\"The body is a machine of unimaginable complexity. You studied its blueprints under Boulder's finest scholars.\"",
    date: "Certified",
    points: 40,
    rarity: "epic",
    category: "certifications",
    icon: Award,
    unlocked: true,
  },
  {
    id: "pmi-teams",
    title: "Forgemaster of Teams",
    description: "PMI: Building High Performance Teams Certification",
    flavor: "\"A chain is only as strong as its weakest link. You learned to make every link unbreakable.\"",
    date: "Certified",
    points: 40,
    rarity: "epic",
    category: "certifications",
    icon: Award,
    unlocked: true,
  },

  // ===== LANGUAGES =====
  {
    id: "cambridge-c1",
    title: "Tongue of the Realm",
    description: "Cambridge C1 Advanced English Certificate",
    flavor: "\"Your words carry the weight of fluency. Diplomats and scholars alike respect this mark.\"",
    date: "Certified",
    points: 40,
    rarity: "epic",
    category: "languages",
    icon: Languages,
    unlocked: true,
  },
  {
    id: "bulgarian-native",
    title: "Mother Tongue",
    description: "Bulgarian Language \u2014 Native Speaker",
    flavor: "\"The language of your homeland flows through you like a river through ancient valleys. Innate and unshakeable.\"",
    date: "Native",
    points: 10,
    rarity: "common",
    category: "languages",
    icon: Languages,
    unlocked: true,
  },
  // Locked language goals
  {
    id: "tefl-cert",
    title: "Teacher of Tongues",
    description: "Get TEFL Certification",
    flavor: "\"To teach a language is to give someone a new world. This seal proves you can.\"",
    date: "???",
    points: 45,
    rarity: "epic",
    category: "certifications",
    icon: Award,
    unlocked: false,
  },
  {
    id: "japanese-n5",
    title: "First Steps in the East",
    description: "Achieve JLPT N5 in Japanese",
    flavor: "\"Hiragana, katakana, and the first kanji \u2014 the gates of a vast linguistic world crack open.\"",
    date: "???",
    points: 35,
    rarity: "rare",
    category: "languages",
    icon: Languages,
    unlocked: false,
  },

  // ===== EXPERIENCE =====
  {
    id: "fitness-instructor",
    title: "Iron Guardian",
    description: "3 Years as Fitness Instructor at Bress",
    flavor: "\"Through discipline of the body, you forged discipline of the mind. Three years of unwavering dedication.\"",
    date: "3 Years",
    points: 75,
    rarity: "epic",
    category: "experience",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "promoter-bress",
    title: "Herald of the Arena",
    description: "Promoter at Bress",
    flavor: "\"Your voice echoed through the halls, drawing warriors and champions to the arena.\"",
    date: "Completed",
    points: 35,
    rarity: "rare",
    category: "experience",
    icon: Briefcase,
    unlocked: true,
  },
  {
    id: "junior-rnd",
    title: "Vanguard of Innovation",
    description: "1 Year Internship \u2014 Junior R&D Specialist & Game Designer (EU Co-Funded Project)",
    flavor: "\"Forged in the crucible of research and creation, backed by the coffers of the European Union itself. A rare appointment.\"",
    date: "1 Year",
    points: 80,
    rarity: "epic",
    category: "experience",
    icon: Brain,
    unlocked: true,
  },
  {
    id: "xplora-marketing",
    title: "Silver-Tongued Captain",
    description: "3 Month Internship at Xplora Marketing \u2014 Marketing & Leadership",
    flavor: "\"You learned the art of persuasion and command. Words became your weapon, leadership your shield.\"",
    date: "3 Months",
    points: 30,
    rarity: "rare",
    category: "experience",
    icon: Briefcase,
    unlocked: true,
  },

  // ===== LOREMASTER =====
  {
    id: "christ-is-king",
    title: "Christ is King",
    description: "Orthodox Way \u2014 Faith as Foundation",
    flavor: "\"Through prayer, tradition, and the light of the Orthodox faith, you walk a path older than empires. The foundation upon which all else is built.\"",
    date: "Always",
    points: 100,
    rarity: "legendary",
    category: "knowledge",
    icon: Cross,
    unlocked: true,
  },
  // Locked Loremaster
  {
    id: "zografou-monastery",
    title: "Pilgrimage to Zografou",
    description: "Visit the Holy Monastery of Zografos (\u0399\u03B5\u03C1\u03AC \u039C\u03BF\u03BD\u03AE \u0396\u03C9\u03B3\u03C1\u03AC\u03C6\u03BF\u03C5), Mount Athos",
    flavor: "\"The Bulgarian monastery on the Holy Mountain. A spiritual fortress where monks have prayed since the 10th century. To step inside is to touch eternity.\"",
    date: "???",
    points: 80,
    rarity: "legendary",
    category: "knowledge",
    icon: Church,
    unlocked: false,
  },
  {
    id: "read-bible",
    title: "The Sacred Text",
    description: "Read the Bible",
    flavor: "\"The most influential book in human history. To read it cover to cover is to journey through millennia of faith, wisdom, and the human quest for meaning. A text that has shaped civilizations, now shaping your understanding of the divine.\"",
    date: "???",
    points: 150,
    rarity: "legendary",
    category: "knowledge",
    icon: BookOpen,
    unlocked: false,
  },

  // ===== GAME DEV & CREATIVE (World Forger) =====
  {
    id: "virtual-production",
    title: "Stage Architect",
    description: "First Virtual Production Stage Game at Breda University \u2014 Concept, Game & Level Designer",
    flavor: "\"Where the physical and digital worlds collide, you were there at the genesis. Concept, design, and craft \u2014 all from your hand.\"",
    date: "Completed",
    points: 65,
    rarity: "epic",
    category: "gamedev",
    icon: Gamepad2,
    unlocked: true,
  },
  {
    id: "unreal-unity-projects",
    title: "Engine Polyglot",
    description: "Multiple small projects in Unreal Engine and Unity",
    flavor: "\"No single forge can contain your craft. Both the Unreal anvil and the Unity loom bear your mark.\"",
    date: "Ongoing",
    points: 35,
    rarity: "rare",
    category: "gamedev",
    icon: Gamepad2,
    unlocked: true,
  },
  {
    id: "quake-levels",
    title: "Mapper of the Old Gods",
    description: "2 Custom Quake Levels Published",
    flavor: "\"In the ancient halls of Quake, your corridors echo with the footsteps of a thousand fraggers. Two maps. Two legacies.\"",
    date: "Published",
    points: 40,
    rarity: "rare",
    category: "gamedev",
    icon: Crosshair,
    unlocked: true,
  },
  {
    id: "pixel-art",
    title: "Pixel Artisan",
    description: "Pixel Art Proficiency \u2014 Can recreate anything that isn't too detailed",
    flavor: "\"One pixel at a time, you paint worlds. The constraint of the grid is your canvas, not your cage.\"",
    date: "Unlocked",
    points: 30,
    rarity: "rare",
    category: "gamedev",
    icon: Palette,
    unlocked: true,
  },
  {
    id: "frontend-dev",
    title: "Apprentice of the Web",
    description: "Front-End Development \u2014 Intermediate Level",
    flavor: "\"The arcane arts of HTML, CSS, and JavaScript bend to your will. Not yet a master, but far beyond a novice.\"",
    date: "Unlocked",
    points: 25,
    rarity: "rare",
    category: "gamedev",
    icon: Code,
    unlocked: true,
  },
  {
    id: "3d-modeling-basic",
    title: "Sculptor of Vertices",
    description: "Basic Level of 3D Modeling Achieved",
    flavor: "\"Polygons bend to your will. The third dimension opens its gates to those patient enough to learn its geometry.\"",
    date: "Unlocked",
    points: 20,
    rarity: "common",
    category: "gamedev",
    icon: Palette,
    unlocked: true,
  },
  {
    id: "board-game-creator",
    title: "Tabletop Artificer",
    description: "Board Game Creator \u2014 Personal Project",
    flavor: "\"Dice, cards, and rules woven from imagination. A world that fits on a table, played by the hands of friends.\"",
    date: "Created",
    points: 35,
    rarity: "rare",
    category: "gamedev",
    icon: Gamepad2,
    unlocked: true,
  },
  {
    id: "angry-birds-game",
    title: "Fledgling Developer",
    description: "Published Angry Birds-style Phone Game with Small Team in 10th Grade",
    flavor: "\"Before you could even vote, you shipped a game to real players. The birds flew, the pigs fell, and a game designer was born.\"",
    date: "10th Grade",
    points: 45,
    rarity: "epic",
    category: "gamedev",
    icon: Gamepad2,
    unlocked: true,
  },

  // ===== SPORTS & MARTIAL ARTS (Arena Champion) =====
  {
    id: "karate-7y",
    title: "Way of the Empty Hand",
    description: "7 Years of Karate Training",
    flavor: "\"Seven years of katas, kumite, and discipline. Your strikes carry the weight of a thousand repetitions.\"",
    date: "7 Years",
    points: 60,
    rarity: "rare",
    category: "sports",
    icon: Swords,
    unlocked: true,
  },
  {
    id: "boxing-2y",
    title: "Iron Fists",
    description: "2 Years of Boxing",
    flavor: "\"The sweet science taught you rhythm, timing, and how to take a punch as well as throw one. Blood, sweat, and the roar of the ring.\"",
    date: "2 Years",
    points: 50,
    rarity: "legendary",
    category: "sports",
    icon: Swords,
    unlocked: true,
  },
  {
    id: "boxing-cage-match",
    title: "Cage Warrior",
    description: "Amateur Unofficial Boxing Match in a Cage",
    flavor: "\"The cage door closed. No referee to save you, no crowd to cheer \u2014 just you, your opponent, and the echo of fists on flesh. You walked out standing.\"",
    date: "Survived",
    points: 60,
    rarity: "legendary",
    category: "sports",
    icon: Swords,
    unlocked: true,
  },
  {
    id: "basketball-3y",
    title: "Court General",
    description: "3 Years of Basketball",
    flavor: "\"The court was your battlefield. Three years of dribbling, dunking, and teamwork.\"",
    date: "3 Years",
    points: 25,
    rarity: "rare",
    category: "sports",
    icon: Target,
    unlocked: true,
  },
  {
    id: "basketball-region-win",
    title: "Regional Champion",
    description: "Winning the Basketball Region School Competition",
    flavor: "\"The final buzzer sounded and your team stood tallest. A regional trophy, earned through sweat and teamwork on the court.\"",
    date: "Champion",
    points: 40,
    rarity: "epic",
    category: "sports",
    icon: Award,
    unlocked: true,
  },
  {
    id: "volleyball-2y",
    title: "Skyward Spike",
    description: "2 Years of Volleyball",
    flavor: "\"You rose above the net and struck with precision. The sand and court alike remember your name.\"",
    date: "2 Years",
    points: 20,
    rarity: "rare",
    category: "sports",
    icon: Target,
    unlocked: true,
  },
  {
    id: "climbing-2y",
    title: "Wallwalker",
    description: "2 Years of Climbing",
    flavor: "\"Gravity is merely a suggestion. Two years of defying it on rock and wall.\"",
    date: "2 Years",
    points: 25,
    rarity: "common",
    category: "sports",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "tennis",
    title: "Summer Rally",
    description: "Multiple Summers of Tennis on Court",
    flavor: "\"The sound of racket on ball under the summer sun \u2014 a seasonal tradition of grace and agility.\"",
    date: "Seasonal",
    points: 15,
    rarity: "common",
    category: "sports",
    icon: Target,
    unlocked: true,
  },

  // ===== CALISTHENICS & STRENGTH (Iron Colossus) =====
  {
    id: "calisthenics-10y",
    title: "Decade of Iron",
    description: "10 Years of Calisthenics and Gym Training",
    flavor: "\"A decade of sweat, calluses, and relentless progression. Your body is a monument to discipline.\"",
    date: "2025",
    points: 80,
    rarity: "legendary",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "handstand",
    title: "Inverted Pillar",
    description: "Handstand \u2014 Unlocked",
    flavor: "\"The world flipped, yet you stood firm. Balance mastered in defiance of gravity.\"",
    date: "Unlocked",
    points: 30,
    rarity: "rare",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "360-spin",
    title: "Whirlwind",
    description: "360 Spin \u2014 Unlocked",
    flavor: "\"A full rotation, airborne and controlled. The crowd holds its breath every time.\"",
    date: "Unlocked",
    points: 45,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "front-flip",
    title: "Forward Surge",
    description: "Front Flip \u2014 Unlocked",
    flavor: "\"Head over heels, launched forward with explosive power. The ground rushes up and you land clean.\"",
    date: "Unlocked",
    points: 35,
    rarity: "rare",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "backflip",
    title: "Reverse Launch",
    description: "Backflip \u2014 Unlocked",
    flavor: "\"Blind faith in your own power. You leap backwards into the void and land on your feet. Every. Single. Time.\"",
    date: "Unlocked",
    points: 40,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "front-lever",
    title: "Horizontal Hold",
    description: "Front Lever \u2014 Unlocked",
    flavor: "\"Suspended in perfect horizontal tension \u2014 a move that humbles even the strongest.\"",
    date: "Unlocked",
    points: 45,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "back-lever",
    title: "Reverse Horizon",
    description: "Back Lever \u2014 Unlocked",
    flavor: "\"Face down, arms locked, body straight as a blade. A testament to core and shoulder mastery.\"",
    date: "Unlocked",
    points: 45,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "back-lever-rings",
    title: "Ring Lord",
    description: "Back Lever on Rings \u2014 Unlocked",
    flavor: "\"The rings swing and sway but you hold like iron. Back lever on the most unstable apparatus \u2014 pure mastery.\"",
    date: "Unlocked",
    points: 55,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "handstand-pushups",
    title: "Inverted Press",
    description: "Handstand Push-Ups \u2014 Unlocked",
    flavor: "\"Pressing your entire bodyweight skyward while inverted. Shoulder strength beyond mortal norms.\"",
    date: "Unlocked",
    points: 40,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "deadlift-150",
    title: "Earthshaker",
    description: "150kg Deadlift",
    flavor: "\"One hundred and fifty kilograms torn from the earth. The ground trembles when you lift.\"",
    date: "PR",
    points: 50,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "power-clean-80",
    title: "Thunder Pull",
    description: "80kg Power Cleans",
    flavor: "\"Explosive force channeled from floor to shoulder in a single violent motion. Eighty kilos, clean.\"",
    date: "PR",
    points: 40,
    rarity: "rare",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "pullup-50kg",
    title: "Gravity Defiler",
    description: "Weighted Pull-Up +50kg",
    flavor: "\"Fifty extra kilograms dangling from your waist and you still rise. Gravity itself bows before your lats.\"",
    date: "PR",
    points: 50,
    rarity: "epic",
    category: "strength",
    icon: Dumbbell,
    unlocked: true,
  },
  {
    id: "calisthenics-competition",
    title: "City's Second Strongest",
    description: "2nd Place \u2014 City Calisthenics Competition",
    flavor: "\"Silver on the podium, but gold in the eyes of those who watched you defy gravity. One step from the top \u2014 next time.\"",
    date: "2nd Place",
    points: 55,
    rarity: "epic",
    category: "strength",
    icon: Award,
    unlocked: true,
  },

  // ===== RUNNING & ENDURANCE =====
  {
    id: "half-marathon",
    title: "Road Warrior",
    description: "Half-Marathon Completed \u2014 2h 17min",
    flavor: "\"21.1 kilometers of asphalt, sweat, and willpower. You crossed the line where many falter.\"",
    date: "2h 17min",
    points: 60,
    rarity: "epic",
    category: "endurance",
    icon: Timer,
    unlocked: true,
  },
  {
    id: "10km-run",
    title: "Strider",
    description: "10km Run \u2014 55 Minutes",
    flavor: "\"Ten thousand meters at pace. The wind knows your rhythm.\"",
    date: "55min",
    points: 35,
    rarity: "rare",
    category: "endurance",
    icon: Timer,
    unlocked: true,
  },
  {
    id: "4km-run",
    title: "Swift Foot",
    description: "4km Run \u2014 19 Minutes",
    flavor: "\"Short, sharp, and fast. A burst of speed that leaves the trail behind in a blur.\"",
    date: "19min",
    points: 20,
    rarity: "common",
    category: "endurance",
    icon: Timer,
    unlocked: true,
  },
  {
    id: "haidushka-downhill",
    title: "Descent Demon",
    description: "Haidushka Pateka, Sliven \u2014 Downhill PR: 23min, 3km, 750m Elevation Loss",
    flavor: "\"Seven hundred and fifty meters of screaming descent in twenty-three minutes. Your knees are made of something stronger than bone.\"",
    date: "23min PR",
    points: 45,
    rarity: "epic",
    category: "endurance",
    icon: Mountain,
    unlocked: true,
  },

  // ===== MOUNTAINEERING (Peak Seeker) =====
  {
    id: "musala-summit",
    title: "Roof of the Balkans",
    description: "Summit Musala \u2014 2,925m, Highest Peak on the Balkans (both on ground and on snow after musala hut)",
    flavor: "\"You stood where the Balkans touch the sky. 2,925 meters of altitude, wind, and triumph. The highest point for a thousand kilometers in every direction.\"",
    date: "Summited",
    points: 80,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "botev-summer",
    title: "Summer Ascent",
    description: "Botev Peak \u2014 Summer Summit \u2014 30km 2100+- Elevation (1-day)",
    flavor: "\"The highest peak of the Central Balkan Range, conquered under the summer sun. Thirty kilometers and over two thousand meters of elevation in a single day \u2014 a test of endurance and will.\"",
    date: "Summited",
    points: 60,
    rarity: "rare",
    category: "mountaineering",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "botev-winter",
    title: "Winter's Defiance",
    description: "Botev Peak \u2014 Solo Summit in Winter Conditions \u2014 30km 2100+- Elevation (1-day)",
    flavor: "\"Alone against the frozen mountain, where blizzards claim the unprepared. You returned with a story the wind still tells.\"",
    date: "Summited",
    points: 70,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "cherni-vruh",
    title: "Night in the Wild",
    description: "Cherni Vruh 2,290m in a Day + Sleeping in the Forest with Only Fire and a Jacket",
    flavor: "\"Totally unprepared, totally alive. You summited, then the forest became your bed. A fire, a jacket, and the stars above \u2014 the most honest night of your life.\"",
    date: "Summited",
    points: 65,
    rarity: "epic",
    category: "mountaineering",
    icon: Flame,
    unlocked: true,
  },
  {
    id: "sliven-full-experience",
    title: "Sliven Full Clear",
    description: "3 Peaks 1,000m+ in One Push \u2014 32km, 2,100m +/- Elevation",
    flavor: "\"Three summits, thirty-two kilometers, and over two thousand meters of elevation change. The Sliven mountains have no more secrets from you.\"",
    date: "Cleared",
    points: 60,
    rarity: "epic",
    category: "mountaineering",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "multiple-2000m",
    title: "Cloud Walker",
    description: "Multiple 2,000m+ Peaks Summited",
    flavor: "\"The mountains know your footsteps. Peak after peak, you climb where the air grows thin and the views grow vast.\"",
    date: "Multiple",
    points: 40,
    rarity: "rare",
    category: "mountaineering",
    icon: Mountain,
    unlocked: true,
  },
  // Locked mountaineering goals
  {
    id: "vihren-summit",
    title: "The Marble Throne",
    description: "Summit Vihren Peak",
    flavor: "\"The marble giant of Pirin awaits. Will you claim its throne?\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "malyovitsa-summer",
    title: "Rila's Fang \u2014 Summer Summit",
    description: "Summit Malyovitsa Peak \u2014 Summer",
    flavor: "\"The sharpest tooth of Rila, conquered under the summer sun. A technical ascent for those who dare.\"",
    date: "???",
    points: 45,
    rarity: "rare",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "malyovitsa-winter",
    title: "Rila's Fang \u2014 Winter Summit",
    description: "Summit Malyovitsa Peak \u2014 Winter",
    flavor: "\"The sharpest tooth of Rila, conquered in winter's grip. Ice, snow, and the challenge of the frozen peak.\"",
    date: "???",
    points: 45,
    rarity: "rare",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "malyovitsa-winter-nw",
    title: "Rila's Fang \u2014 Winter Northwest Edge",
    description: "Summit Malyovitsa Peak \u2014 Winter Summit through the North-West Edge",
    flavor: "\"The most challenging route to Rila's peak. Through the northwest edge in winter \u2014 where only the boldest and most skilled dare to tread. A legendary ascent.\"",
    date: "???",
    points: 80,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "mount-athos",
    title: "The Holy Mountain",
    description: "Summit Mount Athos \u2014 2,033m",
    flavor: "\"The sacred peak where monks and pilgrims have climbed for over a thousand years. A summit of both body and spirit.\"",
    date: "???",
    points: 80,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "mount-olympus",
    title: "Throne of Zeus",
    description: "Summit Mount Olympus \u2014 2,917m",
    flavor: "\"Where the gods of ancient Greece held court. To stand on Mytikas is to stand among legends.\"",
    date: "???",
    points: 75,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "multiple-3000m",
    title: "Above the Clouds",
    description: "Summit Multiple 3,000m+ Peaks",
    flavor: "\"Where the air thins and the sky opens, a new chapter of altitude begins.\"",
    date: "???",
    points: 70,
    rarity: "epic",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "dolomites-all",
    title: "Conqueror of the Dolomites",
    description: "Complete All Major Peaks in the Dolomites",
    flavor: "\"The pale towers of the Italian Alps \u2014 every spire, every via ferrata, conquered and catalogued.\"",
    date: "???",
    points: 120,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "matterhorn",
    title: "The Fang of Zermatt",
    description: "Summit the Matterhorn \u2014 4,478m",
    flavor: "\"The most iconic silhouette in all of alpinism. To stand on its peak is to join a fellowship of the fearless.\"",
    date: "???",
    points: 150,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "mont-blanc",
    title: "Crown of Europe",
    description: "Summit Mont Blanc \u2014 4,808m",
    flavor: "\"The highest peak in Western Europe. Where glaciers guard the summit and only the worthy pass.\"",
    date: "???",
    points: 150,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "mount-fuji",
    title: "Sacred Ascent",
    description: "Summit Mount Fuji \u2014 3,776m",
    flavor: "\"The sacred mountain of Japan. To watch the sunrise from its crater rim is to touch the divine.\"",
    date: "???",
    points: 100,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "ruen-peak",
    title: "Border Sentinel",
    description: "Ruen Peak 2,251m \u2014 Bulgaria Border with Macedonia \u2014 36km 1-day",
    flavor: "\"Where two nations meet, you stood on the peak that watches over both. 2,251 meters of elevation, and a view that spans countries. The border is just a line on a map \u2014 the mountain knows no boundaries.\"",
    date: "Summited",
    points: 45,
    rarity: "rare",
    category: "mountaineering",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "monte-antelao",
    title: "King of the Dolomites",
    description: "Summit Monte Antelao \u2014 3,264m",
    flavor: "\"The regal peak of the Dolomites. 3,264 meters of Italian alpine majesty. To stand on its summit is to claim the crown of one of Europe's most dramatic mountain ranges.\"",
    date: "???",
    points: 90,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "marmolada-punta-penia",
    title: "Queen of the Dolomites",
    description: "Summit Marmolada \u2014 Punta Penia 3,343m",
    flavor: "\"The highest peak in the Dolomites. The queen herself, standing at 3,343 meters. Glaciers cling to her flanks, and those who reach her summit join an elite fellowship of alpine conquerors.\"",
    date: "???",
    points: 95,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "extreme-rila-traverse",
    title: "Rila Grand Traverse",
    description: "Extreme Rila I \u2014 Musala Hut → Sfinksa → Irechek 2,852m → Malka Musala 2,902m → Musala 2,925m → Musala Hut (this is for summer hike)",
    flavor: "\"A traverse through the heart of Rila's highest peaks. Five summits in a single push, each higher than the last, culminating at Musala itself. This is not a hike \u2014 it's a pilgrimage through Bulgaria's alpine soul.\"",
    date: "???",
    points: 110,
    rarity: "legendary",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "malyovitsa-seven-lakes",
    title: "The Seven Lakes Circuit",
    description: "Malyovitsa Hut → Malyovitsa 2,729m → Seven Rila Lakes (this is for summer hike)",
    flavor: "\"From the sharp peak of Malyovitsa to the legendary Seven Rila Lakes. A journey through Rila's most iconic landscapes. Seven mirrors of sky, each reflecting a different shade of alpine beauty.\"",
    date: "???",
    points: 85,
    rarity: "epic",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },
  {
    id: "chumerna-peak",
    title: "Chumerna's Crown",
    description: "Summit Chumerna \u2014 1,536m",
    flavor: "\"A peak that may not touch the clouds, but touches the heart. Chumerna stands as a testament that not all mountains need to be giants to be worthy of conquest.\"",
    date: "???",
    points: 30,
    rarity: "common",
    category: "mountaineering",
    icon: Mountain,
    unlocked: false,
  },

  // ===== CHARITY =====
  {
    id: "charity-run",
    title: "Heart of the Champion",
    description: "Organized & Held Charity Christmas Run \u2014 All proceeds for kids with disabilities in sports",
    flavor: "\"You didn't just run for yourself. You ran so that children who face every day as a battle could find joy in sport. A true champion's deed.\"",
    date: "Organized",
    points: 80,
    rarity: "legendary",
    category: "charity",
    icon: Heart,
    unlocked: true,
  },

  // ===== LICENSES (Motor & Machine) =====
  {
    id: "driving-car",
    title: "Road License",
    description: "Driving License \u2014 Cars (Category B)",
    flavor: "\"The open road beckons. With this license, no highway is beyond your reach.\"",
    date: "Licensed",
    points: 15,
    rarity: "common",
    category: "licenses",
    icon: Car,
    unlocked: true,
  },
  {
    id: "driving-motorcycle",
    title: "Rider's Permit",
    description: "Motorcycle License \u2014 Category A2",
    flavor: "\"Two wheels, one soul. The wind in your face, the engine between your knees. Freedom incarnate.\"",
    date: "Licensed",
    points: 25,
    rarity: "rare",
    category: "licenses",
    icon: Car,
    unlocked: true,
  },
  {
    id: "plane-license",
    title: "Wings of Freedom",
    description: "Small 1/2 People Plane License",
    flavor: "\"The sky is no longer a limit \u2014 it's your domain. With this license, you command the winds, dance with clouds, and see the world from a perspective reserved for gods and pilots. The ultimate freedom.\"",
    date: "???",
    points: 120,
    rarity: "legendary",
    category: "licenses",
    icon: Plane,
    unlocked: false,
  },
  {
    id: "buy-first-car",
    title: "First Wheels",
    description: "Buy the First Car \u2014 <insert name of car later>",
    flavor: "\"The first vehicle that truly belongs to you. Freedom on four wheels, independence in motion. The open road is now yours to claim.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "licenses",
    icon: Car,
    unlocked: false,
  },
  {
    id: "buy-first-motorcycle",
    title: "Two-Wheeled Freedom",
    description: "Buy the First Motorcycle \u2014 <later insert name of motorcycle>",
    flavor: "\"The first machine that answers to your throttle. Wind in your face, engine between your legs, and the world reduced to a ribbon of asphalt ahead. This is freedom in its purest form.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "licenses",
    icon: Car,
    unlocked: false,
  },
  {
    id: "mechanic-beginner",
    title: "Grease Monkey",
    description: "Mechanic \u2014 Beginner Level",
    flavor: "\"Oil under your nails, a wrench in your hand, and the satisfaction of an engine that purrs because of you.\"",
    date: "???",
    points: 20,
    rarity: "common",
    category: "licenses",
    icon: Wrench,
    unlocked: false,
  },
  {
    id: "mechanic-intermediate",
    title: "Engine Whisperer",
    description: "Mechanic \u2014 Intermediate Level",
    flavor: "\"You hear what the engine is saying. Pistons, valves, and timing \u2014 the mechanical symphony bends to your understanding.\"",
    date: "???",
    points: 40,
    rarity: "rare",
    category: "licenses",
    icon: Wrench,
    unlocked: false,
  },

  // ===== SKILLS & HOBBIES (Jack of Trades) =====
  {
    id: "guitar-7y",
    title: "Bard's Resonance",
    description: "Guitar \u2014 7 Years, Intermediate Level",
    flavor: "\"Seven years of strings and calluses. Your melodies carry the weight of a true bard's journey.\"",
    date: "7 Years",
    points: 40,
    rarity: "rare",
    category: "skills",
    icon: Music,
    unlocked: true,
  },
  {
    id: "herbs-beginner",
    title: "Herbalist Novice",
    description: "Herbalism \u2014 Beginner Level",
    flavor: "\"You can tell chamomile from nettle, and that's more than most adventurers can claim. The forest whispers its first secrets.\"",
    date: "Unlocked",
    points: 10,
    rarity: "common",
    category: "skills",
    icon: Flame,
    unlocked: true,
  },
  {
    id: "haiduk",
    title: "Haiduk of Sliven",
    description: "Explored Major Part of the Sliven Mountains",
    flavor: "\"Like the legendary Haiduks who roamed these peaks as outlaws and freedom fighters, you claimed the Blue Rocks as your domain. Every trail, every ridge, every hidden waterfall \u2014 mapped in your memory.\"",
    date: "Explored",
    points: 80,
    rarity: "legendary",
    category: "skills",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "bike-riding",
    title: "Two-Wheel Wanderer",
    description: "Bike Riding \u2014 Unlocked",
    flavor: "\"Simple, elegant, and timeless. The bicycle is humanity's most efficient machine, and you ride it well.\"",
    date: "Unlocked",
    points: 10,
    rarity: "common",
    category: "skills",
    icon: Bike,
    unlocked: true,
  },
  {
    id: "fire-making",
    title: "Flame Keeper",
    description: "Making Fire \u2014 Unlocked",
    flavor: "\"Prometheus brought fire to mankind. You brought it to the campsite. The most primal of all skills, mastered.\"",
    date: "Unlocked",
    points: 10,
    rarity: "common",
    category: "skills",
    icon: Flame,
    unlocked: true,
  },
  {
    id: "photographer-basic",
    title: "Eye of the Lens",
    description: "Photographer \u2014 Basic Level",
    flavor: "\"You learned to see the world through the frame. Composition, light, and the art of freezing a moment in time.\"",
    date: "Unlocked",
    points: 20,
    rarity: "rare",
    category: "skills",
    icon: Camera,
    unlocked: true,
  },
  {
    id: "video-editor-basic",
    title: "Cutter's Craft",
    description: "Video Editor \u2014 Basic Level",
    flavor: "\"Cuts, transitions, timing \u2014 the invisible art that makes moving images sing. Your first edits are done.\"",
    date: "Unlocked",
    points: 20,
    rarity: "rare",
    category: "skills",
    icon: Video,
    unlocked: true,
  },
  {
    id: "stoic-mindset",
    title: "Unshaken Pillar",
    description: "Stoic Mindset \u2014 Unlocked",
    flavor: "\"The obstacle is the way. You endure what must be endured, accept what cannot be changed, and act where action matters. Marcus Aurelius would nod.\"",
    date: "Unlocked",
    points: 30,
    rarity: "rare",
    category: "skills",
    icon: Brain,
    unlocked: true,
  },
  {
    id: "tree-climber",
    title: "Canopy Runner",
    description: "Tree Climber \u2014 Unlocked",
    flavor: "\"While others look up at the branches, you're already among them. A childhood skill that never left your bones.\"",
    date: "Unlocked",
    points: 10,
    rarity: "common",
    category: "skills",
    icon: TreePine,
    unlocked: true,
  },
  {
    id: "youtuber-novice-1",
    title: "First Upload",
    description: "Novice YouTuber I \u2014 Channel Created",
    flavor: "\"The camera is rolling, the mic is hot, and the world is watching. Your first step into the arena of content creation.\"",
    date: "Unlocked",
    points: 15,
    rarity: "common",
    category: "skills",
    icon: Youtube,
    unlocked: true,
  },
  // Locked YouTube goals
  {
    id: "youtuber-novice-2",
    title: "Thousand Eyes",
    description: "Novice YouTuber II \u2014 Reach 1,000 Followers",
    flavor: "\"A thousand souls tuned in to your frequency. The algorithm begins to notice you.\"",
    date: "???",
    points: 30,
    rarity: "rare",
    category: "skills",
    icon: Youtube,
    unlocked: false,
  },
  {
    id: "youtuber-intermediate-1",
    title: "Rising Star",
    description: "Intermediate YouTuber I \u2014 Reach 10,000 Followers",
    flavor: "\"Ten thousand followers. Your voice carries across the digital realm. Sponsors begin to whisper your name.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "skills",
    icon: Youtube,
    unlocked: false,
  },
  {
    id: "youtuber-intermediate-2",
    title: "Silver Screen",
    description: "Intermediate YouTuber II \u2014 Reach 100,000 Followers",
    flavor: "\"One hundred thousand. The Silver Play Button awaits. Your content shapes opinions and inspires action.\"",
    date: "???",
    points: 80,
    rarity: "epic",
    category: "skills",
    icon: Youtube,
    unlocked: false,
  },
  {
    id: "youtuber-advanced",
    title: "Golden Voice",
    description: "Advanced YouTuber \u2014 Reach 1,000,000 Followers",
    flavor: "\"A million souls hang on your every word. The Gold Play Button is yours. You are a force of culture.\"",
    date: "???",
    points: 150,
    rarity: "legendary",
    category: "skills",
    icon: Youtube,
    unlocked: false,
  },
  {
    id: "youtuber-ultimate",
    title: "Digital Deity",
    description: "Ultimate YouTuber \u2014 Reach 10,000,000 Followers",
    flavor: "\"Ten million. Diamond. Your name is spoken in every timezone, your face recognized on every continent. A legend of the digital age.\"",
    date: "???",
    points: 300,
    rarity: "legendary",
    category: "skills",
    icon: Youtube,
    unlocked: false,
  },
  // Locked skills goals
  {
    id: "herbs-intermediate",
    title: "Apothecary's Apprentice",
    description: "Herbalism \u2014 Intermediate Level",
    flavor: "\"Tinctures, poultices, and remedies. The green arts demand patience and knowledge.\"",
    date: "???",
    points: 25,
    rarity: "rare",
    category: "skills",
    icon: Flame,
    unlocked: false,
  },
  {
    id: "herbs-advanced",
    title: "Master Herbalist",
    description: "Herbalism \u2014 Advanced Level",
    flavor: "\"The forest has no more secrets from you. Every root, leaf, and bloom is an open book.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "skills",
    icon: Flame,
    unlocked: false,
  },
  {
    id: "horse-riding",
    title: "Rider of the Steppe",
    description: "Learn to Ride a Horse",
    flavor: "\"Mounted combat may be a stretch, but the bond between rider and steed is as old as civilization.\"",
    date: "???",
    points: 30,
    rarity: "rare",
    category: "skills",
    icon: Flag,
    unlocked: false,
  },
  {
    id: "find-antlers",
    title: "Trophy of the Wild",
    description: "Find Elk Antlers in the Forest",
    flavor: "\"A shed crown of the forest king, hidden among the undergrowth. Only those with a keen eye and patient step will find this treasure.\"",
    date: "???",
    points: 20,
    rarity: "rare",
    category: "skills",
    icon: Target,
    unlocked: false,
  },
  {
    id: "gun-disassemble",
    title: "Armorer Adept",
    description: "Disassemble & Assemble Guns and Rifles \u2014 Advanced",
    flavor: "\"Field strip, clean, reassemble \u2014 blindfolded. The weapon is an extension of the self.\"",
    date: "???",
    points: 40,
    rarity: "epic",
    category: "skills",
    icon: Crosshair,
    unlocked: false,
  },
  {
    id: "parachute-jump",
    title: "Sky Diver",
    description: "Parachute Jump",
    flavor: "\"You leapt from the void and trusted fabric and cord to catch you. The earth rushed up, the wind screamed past, and for a moment you were truly free. Only the brave step into the abyss.\"",
    date: "???",
    points: 70,
    rarity: "epic",
    category: "skills",
    icon: Target,
    unlocked: false,
  },
  {
    id: "jet-ski",
    title: "Wave Rider",
    description: "Drive a Jet Ski",
    flavor: "\"The water became your highway, the jet ski your steed. You carved through waves like a blade through silk, leaving a trail of foam and exhilaration in your wake. The ocean bends to your will.\"",
    date: "Unlocked",
    points: 25,
    rarity: "rare",
    category: "skills",
    icon: Anchor,
    unlocked: true,
  },
  {
    id: "santase-learned",
    title: "Grandfather's Legacy",
    description: "Learn to Play Santanse (Card Game) from My Grandpa at 7 Years Old",
    flavor: "\"At seven years old, your grandfather's hands taught you more than cards \u2014 they taught you tradition, patience, and the art of reading not just the deck, but the player. A game passed down through generations, now living in your hands.\"",
    date: "Learned",
    points: 100,
    rarity: "legendary",
    category: "skills",
    icon: Palette,
    unlocked: true,
  },
  {
    id: "santase-advanced",
    title: "Master of Santase",
    description: "Advanced Santase Player Achieved",
    flavor: "\"You've moved beyond learning to mastery. Every card placement is calculated, every trick anticipated. Your grandfather's lessons have become your own expertise. The table is your domain, and Santase your art.\"",
    date: "Achieved",
    points: 60,
    rarity: "epic",
    category: "skills",
    icon: Palette,
    unlocked: true,
  },
  {
    id: "bilot-advanced",
    title: "Bilot Champion",
    description: "Advanced Bilot Player (Card Game) Achieved",
    flavor: "\"Another card game, another mastery. Bilot demands strategy, memory, and the ability to read your opponents like an open book. You've achieved the advanced level \u2014 the cards bend to your will.\"",
    date: "Achieved",
    points: 55,
    rarity: "epic",
    category: "skills",
    icon: Palette,
    unlocked: true,
  },
  {
    id: "chess-2000-elo",
    title: "Grandmaster Candidate",
    description: "Chess 2000 ELO",
    flavor: "\"Two thousand ELO. You stand among the elite, where every move is a battle of wits, every game a war of attrition. The board is your kingdom, and you are its master strategist. Grandmaster territory awaits.\"",
    date: "???",
    points: 150,
    rarity: "legendary",
    category: "skills",
    icon: Target,
    unlocked: false,
  },
  {
    id: "chess-1000-elo",
    title: "Chess Adept",
    description: "Chess 1000 ELO",
    flavor: "\"One thousand ELO \u2014 the mark of a serious player. You've left the realm of casual games behind and entered the arena where strategy, tactics, and calculation reign supreme. The path to mastery begins here.\"",
    date: "???",
    points: 80,
    rarity: "epic",
    category: "skills",
    icon: Target,
    unlocked: false,
  },
  {
    id: "acquire-sword",
    title: "Blade Bearer",
    description: "Acquire a Sword",
    flavor: "\"A weapon of legend now rests in your hands. Whether forged by a master smith or passed down through generations, this blade represents more than steel \u2014 it is a symbol of honor, skill, and the warrior's path.\"",
    date: "???",
    points: 60,
    rarity: "epic",
    category: "skills",
    icon: Swords,
    unlocked: false,
  },

  // ===== FISHING =====
  {
    id: "fishing-beginner",
    title: "Angler Initiate",
    description: "Fishing \u2014 Beginner Level Cleared",
    flavor: "\"You've cast your first line and felt the tug. The waters have accepted you as one of their own.\"",
    date: "Unlocked",
    points: 15,
    rarity: "common",
    category: "fishing",
    icon: Fish,
    unlocked: true,
  },
  {
    id: "rainbow-trout",
    title: "Prismatic Catch",
    description: "Caught a Basic Rainbow Trout",
    flavor: "\"Scales like stained glass shimmer in the sunlight. Your first real trophy from the current.\"",
    date: "Caught",
    points: 20,
    rarity: "common",
    category: "fishing",
    icon: Fish,
    unlocked: true,
  },
  // Locked fishing goals
  {
    id: "red-salmon",
    title: "Crimson Catch",
    description: "Catch a Red Salmon",
    flavor: "\"The crimson king of the river \u2014 powerful, elusive, and legendary among anglers. One day, the line will sing.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "fishing",
    icon: Fish,
    unlocked: false,
  },
  {
    id: "bluefin-tuna",
    title: "Leviathan of the Deep",
    description: "Catch a Bluefin Tuna",
    flavor: "\"The titan of the open ocean. Hundreds of kilograms of raw power fighting against your will. A battle for the ages.\"",
    date: "???",
    points: 100,
    rarity: "legendary",
    category: "fishing",
    icon: Fish,
    unlocked: false,
  },
  {
    id: "sturgeon",
    title: "Ancient Dweller",
    description: "Catch a Sturgeon",
    flavor: "\"A living fossil from the age of dinosaurs. To hook one is to wrestle with prehistory itself.\"",
    date: "???",
    points: 70,
    rarity: "epic",
    category: "fishing",
    icon: Fish,
    unlocked: false,
  },
  {
    id: "shark",
    title: "Apex Angler",
    description: "Catch a Shark",
    flavor: "\"The predator becomes the prey. Only the boldest anglers dare to pull a shark from the abyss.\"",
    date: "???",
    points: 120,
    rarity: "legendary",
    category: "fishing",
    icon: Fish,
    unlocked: false,
  },
  {
    id: "catfish",
    title: "Whiskered Warrior",
    description: "Catch a Catfish",
    flavor: "\"The bottom-dweller with the whiskers of a cat and the strength of a river god. To hook one is to battle a creature that has survived in the murky depths for eons. A true test of patience and skill.\"",
    date: "???",
    points: 45,
    rarity: "rare",
    category: "fishing",
    icon: Fish,
    unlocked: false,
  },
  {
    id: "pike",
    title: "Freshwater Predator",
    description: "Catch a Pike",
    flavor: "\"The torpedo of the river, all teeth and speed. The pike strikes with the ferocity of a hunter, and to land one is to claim victory over one of freshwater's most formidable predators.\"",
    date: "???",
    points: 25,
    rarity: "common",
    category: "fishing",
    icon: Fish,
    unlocked: false,
  },

  // ===== HUNTING (Hunter's Path) =====
  {
    id: "butcher",
    title: "Blade of the Butcher",
    description: "Butchering \u2014 Intermediate Level",
    flavor: "\"You know your way around a carcass. Clean cuts, precise knowledge of anatomy. A primal skill in a modern world.\"",
    date: "Unlocked",
    points: 25,
    rarity: "rare",
    category: "hunting",
    icon: Crosshair,
    unlocked: true,
  },
  {
    id: "hunting-license",
    title: "Hunter's Seal",
    description: "Get a Hunting License",
    flavor: "\"The ancient bond between human and nature, formalized in paper and ink. With this license, you join the ranks of those who understand the balance between taking and giving, between predator and steward.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "hunting",
    icon: Award,
    unlocked: false,
  },

  // ===== BLACKSMITH (Forge & Anvil) =====
  {
    id: "blacksmith-knife",
    title: "First Blade",
    description: "Make a Knife",
    flavor: "\"The first blade forged by your own hand. Steel shaped by fire and hammer, edge honed by patience. A simple tool, but one that marks the beginning of a smith's journey.\"",
    date: "???",
    points: 20,
    rarity: "common",
    category: "blacksmith",
    icon: Hammer,
    unlocked: false,
  },
  {
    id: "blacksmith-sword",
    title: "Master's Blade",
    description: "Make a Sword",
    flavor: "\"The ultimate test of a smith's skill. A blade that balances beauty and lethality, forged in fire and quenched in purpose. To craft a sword is to create a legend.\"",
    date: "???",
    points: 100,
    rarity: "legendary",
    category: "blacksmith",
    icon: Hammer,
    unlocked: false,
  },
  {
    id: "blacksmith-beginner",
    title: "Spark & Anvil",
    description: "Blacksmithing \u2014 Beginner Level",
    flavor: "\"The forge glows, the hammer falls, and raw metal begins to take shape. The oldest craft calls to you.\"",
    date: "???",
    points: 25,
    rarity: "rare",
    category: "blacksmith",
    icon: Hammer,
    unlocked: false,
  },
  {
    id: "blacksmith-intermediate",
    title: "Journeyman Smith",
    description: "Blacksmithing \u2014 Intermediate Level",
    flavor: "\"The anvil sings under your strikes. Blades, tools, and ornaments \u2014 your forge produces works of both function and beauty.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "blacksmith",
    icon: Hammer,
    unlocked: false,
  },

  // ===== LOCKED LEGACY GOALS =====
  {
    id: "phd",
    title: "Grand Arcanist",
    description: "Earn a PhD or Doctorate",
    flavor: "\"The pinnacle of academic mastery. Only the most dedicated reach these heights.\"",
    date: "???",
    points: 150,
    rarity: "legendary",
    category: "education",
    icon: GraduationCap,
    unlocked: false,
  },
  {
    id: "published-game",
    title: "World Shaper",
    description: "Publish a commercial game title",
    flavor: "\"To create a world from nothing \u2014 that is true power.\"",
    date: "???",
    points: 200,
    rarity: "legendary",
    category: "gamedev",
    icon: Gamepad2,
    unlocked: false,
  },

  // ===== WAYFARER'S ATLAS (EXPLORATION) =====
  {
    id: "explore-belgium",
    title: "Heart of Europe",
    description: "Belgium \u2014 Brussels, Antwerp",
    flavor: "\"Waffles, chocolate, and the seat of the European Union. You walked the cobblestones of kings and bureaucrats alike.\"",
    date: "Explored",
    points: 25,
    rarity: "common",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-germany",
    title: "Iron & Rhine",
    description: "Germany \u2014 Viersen, Essen",
    flavor: "\"The industrial heartland of Europe. From the Ruhr to the Rhine, you walked where steel and culture forged a nation.\"",
    date: "Explored",
    points: 25,
    rarity: "common",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-norway",
    title: "Land of Fjords",
    description: "Norway \u2014 Oslo, Leikanger, Balestrand",
    flavor: "\"The fjords opened their arms and the northern light whispered your name. From Oslo's streets to the stillness of Balestrand.\"",
    date: "Explored",
    points: 30,
    rarity: "rare",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-uk",
    title: "Fog & Empire",
    description: "United Kingdom \u2014 London",
    flavor: "\"The city where history and modernity collide at every corner. Big Ben, the Thames, and the echoes of an empire.\"",
    date: "Explored",
    points: 25,
    rarity: "common",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-denmark",
    title: "Viking Shores",
    description: "Denmark \u2014 Aalborg and the Whole North",
    flavor: "\"The land where Vikings once set sail. You wandered the northern coasts where the wind never stops and the horizons never end.\"",
    date: "Explored",
    points: 25,
    rarity: "common",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-italy",
    title: "Sicilian Sun",
    description: "Italy \u2014 Catania, Taormina, Syracuse",
    flavor: "\"Ancient Greek theaters, Etna's smoke on the horizon, and the warm embrace of Sicilian hospitality.\"",
    date: "Explored",
    points: 30,
    rarity: "rare",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-greece",
    title: "Aegean Wanderer",
    description: "Greece \u2014 Afitos",
    flavor: "\"The cradle of civilization welcomed you. Sun-bleached stone, turquoise waters, and the scent of olive groves.\"",
    date: "Explored",
    points: 20,
    rarity: "common",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-netherlands",
    title: "Lowland Explorer",
    description: "Netherlands \u2014 Amsterdam, Breda, Den Haag, Maastricht, Nuenen (Van Gogh's City), etc.",
    flavor: "\"From the canals of Amsterdam to the village where Van Gogh painted his first masterpieces. The flat lands hold deep stories.\"",
    date: "Explored",
    points: 35,
    rarity: "rare",
    category: "exploration",
    icon: MapPin,
    unlocked: true,
  },
  {
    id: "explore-bulgaria",
    title: "Motherland",
    description: "Bulgaria \u2014 Home Territory",
    flavor: "\"The land of roses, Thracian gold, and mountains that sing. This is where your story began. This is home.\"",
    date: "Home",
    points: 10,
    rarity: "common",
    category: "exploration",
    icon: Flag,
    unlocked: true,
  },

  // ===== SACRED STONES (CATHEDRALS & CHURCHES) =====
  {
    id: "rila-monastery",
    title: "Jewel of the Balkans",
    description: "Rila Monastery, Bulgaria",
    flavor: "\"UNESCO's treasure, nestled in the mountains. Frescoes that have watched over the faithful for centuries. A pilgrimage for the soul.\"",
    date: "Visited",
    points: 35,
    rarity: "epic",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "aleksandar-nevski",
    title: "Golden Domes of Sofia",
    description: "Aleksandar Nevski Cathedral, Sofia",
    flavor: "\"Gold-domed and colossal, the cathedral stands as Sofia's crown jewel. Inside, incense and echoes fill the vaulted darkness.\"",
    date: "Visited",
    points: 25,
    rarity: "rare",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "sveta-sofia",
    title: "The City's Namesake",
    description: "Sveta Sofia Church, Sofia",
    flavor: "\"The church that gave a capital its name. Ancient bricks and whispered prayers that span over fifteen centuries.\"",
    date: "Visited",
    points: 20,
    rarity: "rare",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "grote-kerk-breda",
    title: "The Great Church",
    description: "Grote Kerk, Breda",
    flavor: "\"Gothic spires pierce the Dutch sky. Inside, light filters through centuries-old stained glass onto silent stone.\"",
    date: "Visited",
    points: 20,
    rarity: "common",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "notre-dame-sablon",
    title: "Our Lady of the Sablon",
    description: "\u00C9glise Notre-Dame des Victoires au Sablon, Brussels",
    flavor: "\"A Brabantine Gothic masterpiece in the heart of Brussels. Stained glass windows tell stories older than the nation itself.\"",
    date: "Visited",
    points: 25,
    rarity: "rare",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "st-olav-norway",
    title: "The Northern Chapel",
    description: "St. Olav's Church, Norway",
    flavor: "\"A small church in the land of fjords, where the silence inside rivals the silence of the mountains outside.\"",
    date: "Visited",
    points: 15,
    rarity: "common",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "oslo-cathedral",
    title: "Heart of the Capital",
    description: "Oslo Cathedral, Norway",
    flavor: "\"The spiritual anchor of Norway's capital. Baroque interiors and painted ceilings that have witnessed coronations and prayers alike.\"",
    date: "Visited",
    points: 20,
    rarity: "common",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "viborg-cathedral",
    title: "The Danish Vault",
    description: "Viborg Cathedral, Denmark",
    flavor: "\"Granite and gold leaf in the heart of Jutland. Denmark's oldest cathedral stands as a monument to a millennium of faith.\"",
    date: "Visited",
    points: 20,
    rarity: "common",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "hram-sveta-sofia-sliven",
    title: "Sofia's Echo in Sliven",
    description: "Hram Sveta Sofia, Sliven",
    flavor: "\"A sanctuary of peace in the city at the foot of the Blue Rocks. Faith carved in stone beneath Balkan skies.\"",
    date: "Visited",
    points: 15,
    rarity: "common",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "submerged-church-tvarditsa",
    title: "The Drowned Sanctuary",
    description: "Submerged Church near Tvarditsa, Bulgaria",
    flavor: "\"A church swallowed by the waters, its bell tower still reaching for the sky above the surface. A haunting reminder that even faith can be flooded, but never drowned.\"",
    date: "Visited",
    points: 30,
    rarity: "rare",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },
  {
    id: "drqnovski-manastir",
    title: "Monastery of the Saints",
    description: "Drqnovski Manastir, Bulgaria",
    flavor: "\"A sanctuary of peace and prayer nestled in the Bulgarian mountains. You walked where monks have sought enlightenment for centuries, breathing in the same air of devotion that has filled these halls since ancient times.\"",
    date: "Visited",
    points: 30,
    rarity: "rare",
    category: "sanctuaries",
    icon: Church,
    unlocked: true,
  },

  // ===== HEARTHBOUND (VILLAGE LIFE & HOMESTEAD) =====
  {
    id: "pear-jam",
    title: "Orchard's Gift",
    description: "Homemade Pear Jam",
    flavor: "\"Sweetness preserved in glass, born from patience and autumn's finest harvest. A taste of the old ways.\"",
    date: "Crafted",
    points: 15,
    rarity: "common",
    category: "homestead",
    icon: Wheat,
    unlocked: true,
  },
  {
    id: "quince-jam",
    title: "Golden Preserve",
    description: "Homemade Quince Jam",
    flavor: "\"The quince yields its sweetness only to those who know the slow art of simmering. Amber gold in every jar.\"",
    date: "Crafted",
    points: 15,
    rarity: "common",
    category: "homestead",
    icon: Wheat,
    unlocked: true,
  },
  {
    id: "honey-mead",
    title: "Meadcrafter",
    description: "Homemade Honey Mead",
    flavor: "\"The drink of Vikings and gods alike, brewed by your own hand. Honey, water, time, and a touch of ancient magic.\"",
    date: "Brewed",
    points: 30,
    rarity: "rare",
    category: "homestead",
    icon: Wine,
    unlocked: true,
  },
  {
    id: "cooking-intermediate",
    title: "Seasoned Cook",
    description: "Intermediate Cooking Level \u2014 Wide range of dishes and sweets",
    flavor: "\"Your kitchen is your forge. From hearty stews to delicate sweets, you command flavors with growing confidence.\"",
    date: "Unlocked",
    points: 25,
    rarity: "rare",
    category: "homestead",
    icon: CookingPot,
    unlocked: true,
  },
  // Locked homestead goals
  {
    id: "cured-meat",
    title: "Salt & Smoke",
    description: "Homemade Cured Meat",
    flavor: "\"The ancient art of preservation. Salt, smoke, and patience transform raw flesh into lasting sustenance.\"",
    date: "???",
    points: 30,
    rarity: "rare",
    category: "homestead",
    icon: Beef,
    unlocked: false,
  },
  {
    id: "white-cheese",
    title: "Shepherd's Craft",
    description: "Homemade White Cheese (Sirene)",
    flavor: "\"From fresh milk to crumbly brine-aged perfection. The shepherd's art lives on in your hands.\"",
    date: "???",
    points: 25,
    rarity: "rare",
    category: "homestead",
    icon: Wheat,
    unlocked: false,
  },
  {
    id: "yellow-cheese",
    title: "The Aging Wheel",
    description: "Homemade Cheese (Kashkaval)",
    flavor: "\"Pressed, aged, and golden. The patience of months rewarded with a wheel of rich, nutty flavor.\"",
    date: "???",
    points: 30,
    rarity: "rare",
    category: "homestead",
    icon: Wheat,
    unlocked: false,
  },
  {
    id: "kompoti",
    title: "Summer in a Jar",
    description: "Homemade Kompoti (Fruit Compotes)",
    flavor: "\"Bottled sunshine. Peaches, cherries, and plums preserved in syrup \u2014 a taste of summer in the dead of winter.\"",
    date: "???",
    points: 15,
    rarity: "common",
    category: "homestead",
    icon: Wheat,
    unlocked: false,
  },
  {
    id: "animal-caretaker",
    title: "Beast Keeper",
    description: "Animal Caretaker \u2014 Goats / Cows",
    flavor: "\"To tend to the herd is to tend to life itself. The morning feed, the evening watch \u2014 ancient duties of the land.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "homestead",
    icon: TreePine,
    unlocked: false,
  },
  {
    id: "beekeeper",
    title: "Keeper of the Hive",
    description: "Become a Beekeeper",
    flavor: "\"Thousands of golden workers under your stewardship. Wax, honey, and the quiet hum of a thriving colony.\"",
    date: "???",
    points: 45,
    rarity: "epic",
    category: "homestead",
    icon: Flower2,
    unlocked: false,
  },
  {
    id: "wine-maker",
    title: "Vintner's Art",
    description: "Become a Wine Maker",
    flavor: "\"From vine to barrel to glass. The most patient of crafts, where years of aging produce liquid poetry.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "homestead",
    icon: Wine,
    unlocked: false,
  },
  {
    id: "own-garden",
    title: "Green Thumb",
    description: "Cultivate Your Own Garden",
    flavor: "\"Seeds in the soil, hands in the dirt, sun on your back. The simplest and most rewarding of all quests.\"",
    date: "???",
    points: 25,
    rarity: "rare",
    category: "homestead",
    icon: Flower2,
    unlocked: false,
  },
  {
    id: "own-dog",
    title: "Loyal Companion",
    description: "Get Your Own Dog",
    flavor: "\"Every adventurer needs a faithful companion. One who greets you at the door and follows you into the unknown.\"",
    date: "???",
    points: 20,
    rarity: "common",
    category: "homestead",
    icon: Dog,
    unlocked: false,
  },
  {
    id: "build-house",
    title: "Stone by Stone",
    description: "Build a House (or Part of One)",
    flavor: "\"To lay stone upon stone and call it home. The greatest craft of all \u2014 building the walls that shelter your story.\"",
    date: "???",
    points: 100,
    rarity: "legendary",
    category: "homestead",
    icon: Home,
    unlocked: false,
  },

  // ===== TALES & TRIALS (Random Adventures & Stories) =====
  {
    id: "ww2-bunkers",
    title: "Echoes of the Atlantic Wall",
    description: "Explored Abandoned WW2 Bunkers in Northern Denmark",
    flavor: "\"Concrete ghosts half-swallowed by sand and sea. You stepped where soldiers once kept watch over an ocean that carried both fear and hope.\"",
    date: "Explored",
    points: 35,
    rarity: "rare",
    category: "tales",
    icon: Skull,
    unlocked: true,
  },
  {
    id: "stranded-viersen",
    title: "The Long Cold Night",
    description: "Stranded at a Train Station for an Entire Winter Night \u2014 Viersen, Germany",
    flavor: "\"No trains, no taxis, no shelter but the station's cold bench. The wind howled through Viersen as you endured the longest night, waiting for a dawn that seemed to never come.\"",
    date: "Survived",
    points: 30,
    rarity: "rare",
    category: "tales",
    icon: Snowflake,
    unlocked: true,
  },
  {
    id: "bike-sliven-tvarditsa",
    title: "The Frozen Ride",
    description: "Bike Ride 60km Over 2 Days \u2014 Sliven to Tvarditsa, Pouring Rain, 0\u00B0C",
    flavor: "\"Sixty kilometers of mud, freezing rain, and sheer determination. Your legs screamed, your hands went numb, but you pedaled on through the Bulgarian winter like a man possessed.\"",
    date: "Endured",
    points: 45,
    rarity: "epic",
    category: "tales",
    icon: Bike,
    unlocked: true,
  },
  {
    id: "bike-breda-antwerp",
    title: "Cross-Border Sprint",
    description: "Bike Ride 60km in One Day \u2014 Breda (NL) to Antwerp (BE) through Nuenen",
    flavor: "\"From the Netherlands to Belgium in a single push, passing through the village where Van Gogh once walked. Sixty kilometers, two countries, one day, zero excuses.\"",
    date: "Completed",
    points: 40,
    rarity: "rare",
    category: "tales",
    icon: Bike,
    unlocked: true,
  },
  {
    id: "baba-vida-fortress",
    title: "Guardian of the North",
    description: "Baba Vida Fortress in Vidin \u2014 Northernmost City in Bulgaria",
    flavor: "\"The last bastion before the border. A medieval fortress that has watched over the Danube for a thousand years. You stood where empires clashed and history was written in stone.\"",
    date: "Visited",
    points: 30,
    rarity: "rare",
    category: "tales",
    icon: Castle,
    unlocked: true,
  },
  {
    id: "maastricht-underground",
    title: "Beneath the Surface",
    description: "Maastricht \u2014 North Caves Maastricht Underground",
    flavor: "\"You descended into the depths where miners once carved passages through limestone. The underground city revealed its secrets, and you emerged knowing that some of the greatest adventures happen beneath our feet.\"",
    date: "Explored",
    points: 35,
    rarity: "rare",
    category: "tales",
    icon: Mountain,
    unlocked: true,
  },
  {
    id: "abandoned-sliven",
    title: "Urban Explorer",
    description: "Abandoned Places in Sliven \u2014 Factory, Hospitals, UFO, Koludruma",
    flavor: "\"The ghosts of industry and forgotten purpose. You walked through corridors where machines once roared and healers once tended. The UFO structure, the empty hospitals, the silent factory \u2014 each a monument to what was and what might be again.\"",
    date: "Explored",
    points: 40,
    rarity: "epic",
    category: "tales",
    icon: Building2,
    unlocked: true,
  },
  {
    id: "pet-bear",
    title: "Beast Tamer",
    description: "Pet a Bear",
    flavor: "\"To touch the wild without fear. The bear's fur beneath your hand, its breath warm, its power contained but never tamed. A moment where predator and human meet in mutual respect.\"",
    date: "???",
    points: 60,
    rarity: "epic",
    category: "tales",
    icon: Dog,
    unlocked: false,
  },
  {
    id: "pet-elephant",
    title: "Gentle Giant",
    description: "Pet an Elephant",
    flavor: "\"The largest land mammal, gentle despite its size. To feel the rough texture of its hide, to look into its ancient eyes \u2014 you touched a creature that remembers what humans have forgotten.\"",
    date: "???",
    points: 50,
    rarity: "epic",
    category: "tales",
    icon: Dog,
    unlocked: false,
  },
  {
    id: "obshtaka-tales",
    title: "Dormitory Chronicles",
    description: "Tales of Obshtaka in Sofia \u2014 Living in a Student Dorm",
    flavor: "\"The Obshtaka \u2014 where students become family, where late-night study sessions turn into lifelong memories, and where you learned that home is not a place but the people you share it with. The walls of that dormitory hold more stories than any library.\"",
    date: "Lived",
    points: 35,
    rarity: "rare",
    category: "tales",
    icon: Home,
    unlocked: true,
  },
  {
    id: "village-forest-explorer",
    title: "Forest Wanderer",
    description: "Exploring Forest Above My Village Area",
    flavor: "\"The woods above your village became your second home. Every trail, every clearing, every hidden grove \u2014 you mapped them all. The forest whispered its secrets to you, and you listened. Nature's classroom, open 24/7.\"",
    date: "Explored",
    points: 30,
    rarity: "rare",
    category: "tales",
    icon: TreePine,
    unlocked: true,
  },
  {
    id: "snails-pope-chef",
    title: "Divine Cuisine",
    description: "Collect Snails and a Pope Who Is Also a Chef Cooked Them",
    flavor: "\"A tale that sounds like legend but is pure truth. You gathered snails from the earth, and a man of the cloth \u2014 who also wields a chef's knife \u2014 transformed them into a feast. Where faith meets flavor, where the sacred and the savory unite. A meal blessed twice over.\"",
    date: "Feasted",
    points: 40,
    rarity: "epic",
    category: "tales",
    icon: CookingPot,
    unlocked: true,
  },
]
